"""initial

Revision ID: 0a56824ec859
Revises:
Create Date: 2025-11-19 03:59:42.632436

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a56824ec859"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
